### ISSUE TITLE
lib.cortex.CortexApiException: {"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}

### ISSUE THREAD

**Issue by zabir-nabil** [Emotiv/cortex-v2-example#33]
I'm trying to run the python example, but getting this error repeatedly. I have an emotiv insight, activated the BASIC license, and BCI license.

There are similar issues, but none seems to provide a working solution.

`(emotiv) C:\Users\Zabir\Desktop\emotiv\cortex-v2-example-master\cortex-v2-example-master\python>python example.py
** USER LOGIN **
Sending request:
{"jsonrpc": "2.0", "method": "getUserLogin", "params": {}, "id": 1}
sent; awaiting response
lib.cortex resp:
{'currentOSUId': '1001', 'currentOSUsername': 'Zabir', 'loggedInOSUId': '1001', 'loggedInOSUsername': 'Zabir', 'username': 'zabir_nabil'}
** GET CORTEX INFO **
Sending request:
{"jsonrpc": "2.0", "method": "getCortexInfo", "params": {}, "id": 2}
sent; awaiting response
lib.cortex resp:
{'id': 2, 'jsonrpc': '2.0', 'result': {'buildDate': '2019-08-01T15:09:03', 'buildNumber': '01f5820', 'version': '2.1.0'}}
** HAS ACCESS RIGHT **
Sending request:
{"jsonrpc": "2.0", "method": "requestAccess", "params": {"clientId": "zVGvkZG66axd2MsjKg8azGB8dZtnC5nVJyWV3xJz", "clientSecret": "yJG5GhzRIuzSmhWmjpjJg6VbhZXypzTIyfNZFlGVxAZLEzVjwpa6NEYvbCydp0Kbo6e4uPbJc1Fr9YYNgNlTKukpAByTjjPeo4FsKN1RWA8ewfEidmyYTEqCwErWYH2T"}, "id": 3}
sent; awaiting response
lib.cortex resp:
{'id': 3, 'jsonrpc': '2.0', 'result': {'accessGranted': True, 'message': 'The User has access right to this application.'}}
** REQUEST ACCESS **
Sending request:
{"jsonrpc": "2.0", "method": "requestAccess", "params": {"clientId": "zVGvkZG66axd2MsjKg8azGB8dZtnC5nVJyWV3xJz", "clientSecret": "yJG5GhzRIuzSmhWmjpjJg6VbhZXypzTIyfNZFlGVxAZLEzVjwpa6NEYvbCydp0Kbo6e4uPbJc1Fr9YYNgNlTKukpAByTjjPeo4FsKN1RWA8ewfEidmyYTEqCwErWYH2T"}, "id": 4}
sent; awaiting response
lib.cortex resp:
{'id': 4, 'jsonrpc': '2.0', 'result': {'accessGranted': True, 'message': 'The User has access right to this application.'}}
** AUTHORIZE **
Sending request:
{"jsonrpc": "2.0", "method": "authorize", "params": {"clientId": "zVGvkZG66axd2MsjKg8azGB8dZtnC5nVJyWV3xJz", "clientSecret": "yJG5GhzRIuzSmhWmjpjJg6VbhZXypzTIyfNZFlGVxAZLEzVjwpa6NEYvbCydp0Kbo6e4uPbJc1Fr9YYNgNlTKukpAByTjjPeo4FsKN1RWA8ewfEidmyYTEqCwErWYH2T"}, "id": 5}
sent; awaiting response
lib.cortex resp:
{'id': 5, 'jsonrpc': '2.0', 'result': {'cortexToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS56YWJpcl9uYWJpbC5icmFpbmVjdCIsImFwcFZlcnNpb24iOiIxLjAiLCJleHAiOjE1NjY0ODA4MDQsImxpY2Vuc2VJZCI6ImZlMWZmMGU3LTc5YzgtNDEzZC1hOGVhLTg4Mzg2OTEyYWMxOCIsIm5iZiI6MTU2NjIyMTYwNCwidXNlcklkIjoiMGFiOWY3OTUtNWFhZS00MTMxLWE1MTAtMTJlOTYzNzY4MTM4IiwidXNlcm5hbWUiOiJ6YWJpcl9uYWJpbCIsInZlcnNpb24iOiIyLjAifQ==.5FtvYz0RxBmPW2nHQTfFnrhb1gKseBkEdejGTNc3/2g='}}
** GET LICENSE INFO **
Sending request:
{"jsonrpc": "2.0", "method": "getLicenseInfo", "params": {"cortexToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS56YWJpcl9uYWJpbC5icmFpbmVjdCIsImFwcFZlcnNpb24iOiIxLjAiLCJleHAiOjE1NjY0ODA4MDQsImxpY2Vuc2VJZCI6ImZlMWZmMGU3LTc5YzgtNDEzZC1hOGVhLTg4Mzg2OTEyYWMxOCIsIm5iZiI6MTU2NjIyMTYwNCwidXNlcklkIjoiMGFiOWY3OTUtNWFhZS00MTMxLWE1MTAtMTJlOTYzNzY4MTM4IiwidXNlcm5hbWUiOiJ6YWJpcl9uYWJpbCIsInZlcnNpb24iOiIyLjAifQ==.5FtvYz0RxBmPW2nHQTfFnrhb1gKseBkEdejGTNc3/2g="}, "id": 6}
sent; awaiting response
lib.cortex resp:
{'id': 6, 'jsonrpc': '2.0', 'result': {'isOnline': True, 'license': {'applications': ['com.emotiv.sdk.basic'], 'billingFrom': '2019-07-31T06:00:00.000+06:00', 'billingTo': '2029-07-28T06:00:00.000+06:00', 'deviceInfo': {'deviceLimit': 3, 'devicesPerSeat': 3, 'sessionLimit': {'day': None, 'month': None, 'year': None}}, 'expired': False, 'extenderLimit': 6, 'hardLimitTime': '2019-09-08T05:59:59.999+06:00', 'isCommercial': False, 'licenseId': 'fe1ff0e7-79c8-413d-a8ea-88386912ac18', 'licenseName': 'Basic License', 'localQuota': 0, 'maxDebit': None, 'scopes': [''], 'seatCount': 1, 'sessionCount': 0, 'softLimitTime': '2019-09-01T05:59:59.999+06:00', 'totalDebit': 0, 'totalRegisteredDevices': 1, 'validFrom': '2019-07-31T06:00:00.000+06:00', 'validTo': '2029-07-29T05:59:59.999+06:00'}}}
** QUERY HEADSETS **
Sending request:
{"jsonrpc": "2.0", "method": "queryHeadsets", "params": {}, "id": 7}
sent; awaiting response
lib.cortex found headsets ['INSIGHT-A1D202AA']
lib.cortex resp:
{'id': 7, 'jsonrpc': '2.0', 'result': [{'connectedBy': 'bluetooth', 'customName': '', 'dongle': '0', 'firmware': '930', 'id': 'INSIGHT-A1D202AA', 'motionSensors': ['Q0', 'Q1', 'Q2', 'Q3', 'ACCX', 'ACCY', 'ACCZ', 'MAGX', 'MAGY', 'MAGZ'], 'sensors': ['AF3', 'T7', 'Pz', 'T8', 'AF4'], 'settings': {'eegRate': 128, 'eegRes': 14, 'memsRate': 64, 'memsRes': 14, 'mode': 'INSIGHT'}, 'status': 'connected'}]}
** CREATE SESSION **
Sending request:
{"jsonrpc": "2.0", "method": "createSession", "params": {"cortexToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS56YWJpcl9uYWJpbC5icmFpbmVjdCIsImFwcFZlcnNpb24iOiIxLjAiLCJleHAiOjE1NjY0ODA4MDQsImxpY2Vuc2VJZCI6ImZlMWZmMGU3LTc5YzgtNDEzZC1hOGVhLTg4Mzg2OTEyYWMxOCIsIm5iZiI6MTU2NjIyMTYwNCwidXNlcklkIjoiMGFiOWY3OTUtNWFhZS00MTMxLWE1MTAtMTJlOTYzNzY4MTM4IiwidXNlcm5hbWUiOiJ6YWJpcl9uYWJpbCIsInZlcnNpb24iOiIyLjAifQ==.5FtvYz0RxBmPW2nHQTfFnrhb1gKseBkEdejGTNc3/2g=", "headset": "INSIGHT-A1D202AA", "status": "active"}, "id": 8}
sent; awaiting response
Got error in createSession with params {'cortexToken': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBJZCI6ImNvbS56YWJpcl9uYWJpbC5icmFpbmVjdCIsImFwcFZlcnNpb24iOiIxLjAiLCJleHAiOjE1NjY0ODA4MDQsImxpY2Vuc2VJZCI6ImZlMWZmMGU3LTc5YzgtNDEzZC1hOGVhLTg4Mzg2OTEyYWMxOCIsIm5iZiI6MTU2NjIyMTYwNCwidXNlcklkIjoiMGFiOWY3OTUtNWFhZS00MTMxLWE1MTAtMTJlOTYzNzY4MTM4IiwidXNlcm5hbWUiOiJ6YWJpcl9uYWJpbCIsInZlcnNpb24iOiIyLjAifQ==.5FtvYz0RxBmPW2nHQTfFnrhb1gKseBkEdejGTNc3/2g=', 'headset': 'INSIGHT-A1D202AA', 'status': 'active'}:
{"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}
Traceback (most recent call last):
  File "example.py", line 45, in <module>
    test()
  File "example.py", line 40, in test
    asyncio.run(do_stuff(cortex))
  File "C:\Anaconda_3\envs\emotiv\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Anaconda_3\envs\emotiv\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "example.py", line 24, in do_stuff
    headset_id=cortex.headsets[0])
  File "C:\Users\Zabir\Desktop\emotiv\cortex-v2-example-master\cortex-v2-example-master\python\lib\cortex.py", line 254, in create_session
    resp = await self.send_command('createSession', **params)
  File "C:\Users\Zabir\Desktop\emotiv\cortex-v2-example-master\cortex-v2-example-master\python\lib\cortex.py", line 135, in send_command
    raise CortexApiException(resp)
lib.cortex.CortexApiException: {"error":{"code":-32019,"message":"Session limit on this device has been reached."},"id":8,"jsonrpc":"2.0"}`

**Comment by zabir-nabil** [comment]
There are some issues in the cortex.py code, I was able to get the data with the following changes:

`async def authorize(self, license_id=None, debit=None):`

to

'async def authorize(self, license_id=None, debit=100):'

and
        
`if auth and not self.auth_token:
            await self.authorize()
`

to

`if auth:
            await self.authorize()
`
